### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [Dbz/kube-aliases#10]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose one.

**Comment by patmessina** [comment]
This is originally Dbz project. So whatever he wants to do. Im partial to MIT or GPL.

**Comment by Dbz** [comment]
I'm an MIT guy personally, so I will make a PR with an MIT license

**Comment by unixorn** [comment]
Cool. Once you do that either bump this issue or make a PR on [unixorn/awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) to add it there and I'll merge it, whatever's less hassle for you.

**Comment by patmessina** [comment]
https://github.com/Dbz/kube-aliases/pull/17

Working on it a couple years later.....
