### ISSUE TITLE
[Issue] Duplicate use of alias

### ISSUE THREAD

**Issue by HenrikStanley** [Dbz/kube-aliases#11]
The alias kgs is mapped to both:
kubectl get secrets
kubectl get services

Since kubectl get services is the last alias mapped it wins out.
A new alias should be chosen for kubectl get secrets such as kgse

**Comment by patmessina** [comment]
Issue was fixed with commit b8c929a7b1484a8d422c9b091aecb9a6b7e184e8

Thank you for bringing it up.

**Comment by HenrikStanley** [comment]
That is awesome, as a note, it is not updated in the help file, so when running khelp usage it still shows the old alias, if the help gets updated it would ensure that people don't mistake it as a still existing issue.

**Comment by patmessina** [comment]
Fixed. In the future we are hoping to automate the creation of the aliases and the help. That way we (hopefully) do not run into this again.
